// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package gi

const (
	Version     = "v1.3.25"
	GitCommit   = "2304d96a"         // the commit JUST BEFORE the release
	VersionDate = "2023-10-24 18:29" // UTC
)
