// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package gi

const (
	Version     = "v1.3.22"
	GitCommit   = "c78daec7"         // the commit JUST BEFORE the release
	VersionDate = "2023-08-24 19:05" // UTC
)
