// WARNING: auto-generated by Makefile release target -- run 'make release' to update

package gi

const (
	Version     = "v1.3.23"
	GitCommit   = "b819e607"         // the commit JUST BEFORE the release
	VersionDate = "2023-10-07 02:19" // UTC
)
